name: qbi2021
channels:
  - defaults
  - anaconda
  - damianavila82
  - satra
  - menpo
  - pluraldatum
  - glemaitre
  - pytorch
  - conda-forge
  - defaults
  - simpleitk
dependencies:
  - conda
  - python=3.7
  - conda-env
  - conda-build
  - conda-verify
  - matplotlib
  - _ipyw_jlab_nb_ext_conf
  - anaconda
  - anaconda-navigator
  - navigator-updater
  - numpy
  - bokeh
  - graphviz
  - rise
  - pandas
  - python-graphviz
  - pydot
  - plotly
  - ffmpeg
  - tensorflow==1.15
  - keras
  - pytorch
  - itk
  - SimpleITK
  - ipyvolume
  - ffmpeg
  - jupyter_contrib_nbextensions
  - tornado
  - tifffile
  - pip
  - scipy
  - scikit-image
  - dask-image
  - pip: 
    - webcolors
    - itkwidgets
    - plotly
