# Book settings
title: Quantitative Big Imaging - Introduction

author: Anders Kaestner
#logo: 'images/logo.png'

execute:
  timeout: -1
  execute_notebooks: cache

latex:
  latex_documents:
     targetname: QBI-Lecture01-Introduction.tex
