# Book settings
title: Quantitative Big Imaging - Building and Augmenting Datasets

author: Anders Kaestner
#logo: 'images/logo.png'

execute:
  timeout: -1
  execute_notebooks: auto

latex:
  latex_documents:
     targetname: QBI-Lecture03-Datasets.tex
